# Generated by Django 6.1 on 2026-08-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('garbage', 'Garbage'), ('overflowing_bin', 'Overflowing Bin'), ('illegal_dumping', 'Illegal Dumping'), ('drainage', 'Drainage Issue'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='garbage_images/')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
