# Generated by Django 6.1 on 2026-08-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_latitude_complaint_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_confidence',
            field=models.IntegerField(default=85),
        ),
    ]
