# Generated by Django 6.1 on 2026-08-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_feedback_complaint_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolved_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolved_images/'),
        ),
    ]
