# Generated by Django 6.1 on 2026-08-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaint_resolved_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_waste_type',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Wet Waste', 'Wet Waste'), ('Dry Waste', 'Dry Waste'), ('E-Waste', 'E-Waste'), ('Glass', 'Glass'), ('Metal', 'Metal'), ('Construction Waste', 'Construction Waste'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
