# Generated by Django 6.1 on 2026-08-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_complaint_ai_waste_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20),
        ),
    ]
