# Generated by Django 6.1 on 2026-08-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_complaint_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='detected_area',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='service_available',
            field=models.BooleanField(default=False),
        ),
    ]
