# Generated by Django 6.1 on 2026-08-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_complaint_detected_area_complaint_service_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Waiting for Batch', 'Waiting for Batch'), ('Ready for Pickup', 'Ready for Pickup'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=50),
        ),
    ]
