# Generated by Django 6.1 on 2026-08-24 04:08

from django.db import migrations, models


def move_old_batch_statuses(apps, schema_editor):
    Complaint = apps.get_model('complaints', 'Complaint')

    for complaint in Complaint.objects.filter(status__in=['Waiting for Batch', 'Ready for Pickup']):
        complaint.operation_status = complaint.status
        complaint.batch_area = complaint.location or complaint.detected_area or 'Unassigned'
        complaint.status = 'Pending'
        complaint.save(update_fields=['operation_status', 'batch_area', 'status'])


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='batch_area',
            field=models.CharField(default='Unassigned', max_length=150),
        ),
        migrations.AddField(
            model_name='complaint',
            name='operation_status',
            field=models.CharField(choices=[('Waiting for Batch', 'Waiting for Batch'), ('Ready for Pickup', 'Ready for Pickup'), ('Vehicle Assigned', 'Vehicle Assigned'), ('Cleanup Done', 'Cleanup Done')], default='Waiting for Batch', max_length=50),
        ),
        migrations.RunPython(move_old_batch_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=50),
        ),
    ]
