# Generated by Django 6.1 on 2026-08-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_complaint_batch_area_complaint_operation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='fake_risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_live_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='verification_status',
            field=models.CharField(default='Pending Verification', max_length=50),
        ),
    ]
